In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_excel('S04AC223.xlsx')
df.head()

,AC_No,ACNameEn,PollingBoothNo,SectionNo,votersl,houseno,VIDNo,VoterNameEng,Votername,Sex,relationNameEng,relationname,relation,Age,SectionName,SectionNameEng,PollingStationAddressEn,PollingStationAddress
0,223,Aurangabad,1,1,1,1,NCY2630614,saurav kumar,सौरव कुमार,Male,ashok prasad,अशोक प्रसाद,Father,22,जम्होर,Jamhor,Uchcha Vighalay Jamhor,उच्च विघालय जम्होर
1,223,Aurangabad,1,1,2,2,NCY2464733,Sanjeev kumar Pandey,संजीव कुमार पाण्डेय,Male,Suresh Pandey,सुरेश पाण्डेय,Father,27,जम्होर,Jamhor,Uchcha Vighalay Jamhor,उच्च विघालय जम्होर
2,223,Aurangabad,1,1,3,2,NCY2467843,Durgawati Devi,दुर्गावती` देवी,Female,Dudhnath paswan,दुधनाथ पासवान,Husband,57,जम्होर,Jamhor,Uchcha Vighalay Jamhor,उच्च विघालय जम्होर
3,223,Aurangabad,1,1,4,2,NCY2467850,Dudhnath Paswan,दुधनाथ पासवान,Male,chhedi Paswan,छेदी पासवान,Father,68,जम्होर,Jamhor,Uchcha Vighalay Jamhor,उच्च विघालय जम्होर
4,223,Aurangabad,1,1,5,3,NCY0415406,Sanjit kumar,संजीत कुमार,Male,Ramanand Paswan,रामानन्द पासवान,Father,24,जम्होर,Jamhor,Uchcha Vighalay Jamhor,उच्च विघालय जम्होर

In [4]:
df.shape

(93384, 18)

In [5]:
df.PollingBoothNo.max()

100

In [6]:
df.isnull().sum()

AC_No                          0
ACNameEn                   11677
PollingBoothNo                 0
SectionNo                      0
votersl                        0
houseno                        0
VIDNo                          0
VoterNameEng                   0
Votername                      0
Sex                            0
relationNameEng                0
relationname                   0
relation                       0
Age                            0
SectionName                11677
SectionNameEng             11677
PollingStationAddressEn    11677
PollingStationAddress      11677
dtype: int64

In [16]:
df[['FirstNameEng','MidNameEng','LastNameEng']]=df.VoterNameEng.str.split(' ',2,expand=True)

In [17]:
df[['VoterNameEng','FirstNameEng','MidNameEng','LastNameEng']]

               VoterNameEng FirstNameEng MidNameEng LastNameEng
0              saurav kumar       saurav      kumar        None
1      Sanjeev kumar Pandey      Sanjeev      kumar      Pandey
2            Durgawati Devi    Durgawati       Devi        None
3           Dudhnath Paswan     Dudhnath     Paswan        None
4              Sanjit kumar       Sanjit      kumar        None
...                     ...          ...        ...         ...
93379           Munni Singh        Munni      Singh        None
93380     Sunil Kumar Singh        Sunil      Kumar       Singh
93381          Pradip Kumar       Pradip      Kumar        None
93382   Santosh Kumar Singh      Santosh      Kumar       Singh
93383           Sunita Devi       Sunita       Devi        None

[93384 rows x 4 columns]

In [44]:
df.loc[(df.VoterNameEng=='Gajala Praveen') & (df.PollingBoothNo==19)].relationname

17187    सरताज अहमद
Name: relationname, dtype: object

In [70]:
df.PollingBoothNo.max()

100

In [72]:
df.loc[(df.Sex=='Female') & (df.Age<30)].groupby('PollingBoothNo').PollingBoothNo.count().max()

204

In [50]:
df.columns

Index(['AC_No', 'ACNameEn', 'PollingBoothNo', 'SectionNo', 'votersl',
       'houseno', 'VIDNo', 'VoterNameEng', 'Votername', 'Sex',
       'relationNameEng', 'relationname', 'relation', 'Age', 'SectionName',
       'SectionNameEng', 'PollingStationAddressEn', 'PollingStationAddress',
       'FirstNameEng', 'MidNameEng', 'LastNameEng'],
      dtype='object')

In [76]:
df['FirstNameEng'].value_counts()

Ram           1476
Mohammad      1377
Sunita         552
Sanjay         534
Shanti         520
              ...
Munnan           1
Firoza           1
Lakhaatiya       1
Dewanand         1
Tabarasum        1
Name: FirstNameEng, Length: 14703, dtype: int64

In [90]:
lastname_count=df['LastNameEng'].value_counts()
lastname_count

Singh         3551
Devi          1170
Yadav          958
Ram            635
               448
              ...
bhaagat          1
Ikawal           1
PRABHAT          1
Purushotam       1
Beldar           1
Name: LastNameEng, Length: 1022, dtype: int64

In [94]:
lastname_percent=df['LastNameEng'].value_counts(normalize=True)*100
lastname_percent

Singh         25.012327
Devi           8.241178
Yadav          6.747904
Ram            4.472776
               3.155596
                ...
bhaagat        0.007044
Ikawal         0.007044
PRABHAT        0.007044
Purushotam     0.007044
Beldar         0.007044
Name: LastNameEng, Length: 1022, dtype: float64

In [110]:
df.groupby(['PollingBoothNo','SectionNo','houseno']).VIDNo.count()

PollingBoothNo  SectionNo  houseno
1               1          04          2
                           1           1
                           10         12
                           11         15
                           12          9
                                      ..
100             3          5           5
                           6          13
                           7          15
                           8          40
                           9           5
Name: VIDNo, Length: 13136, dtype: int64

In [114]:
total_family=13136
total_voter=df.VIDNo.count()

In [116]:
avg_family_size=total_voter/total_family
avg_family_size

7.1090133982947625

In [146]:
df.SectionNameEng.value_counts().sort_values()

Bhuiya Bigaha            1
Devariya Rustam          1
Tole Bhuiya  Vigha       1
Tola Rangal Bigaha       1
Devariya Kala            1
                      ...
Badawan               1664
Kushi                 1868
Fesar                 2093
Jhikatiya             2185
Jamhor                5241
Name: SectionNameEng, Length: 117, dtype: int64

In [5]:
df.groupby([df.PollingBoothNo,df.SectionNo,df.houseno]).df[df.Age==df.Age.max()]

AttributeError: 'DataFrameGroupBy' object has no attribute 'df'

In [13]:
df.groupby([df.PollingBoothNo,df.SectionNo,df.houseno]).apply(lambda df:df[df.Age==df.Age.max()])

                                        AC_No    ACNameEn  PollingBoothNo  \
PollingBoothNo SectionNo houseno
1              1         04      1003     223  Aurangabad               1
                         1       0        223  Aurangabad               1
                         10      76       223  Aurangabad               1
                         11      84       223  Aurangabad               1
                         12      103      223  Aurangabad               1
...                                       ...         ...             ...
100            3         6       92906    223  Aurangabad             100
                         7       92930    223  Aurangabad             100
                         8       92934    223  Aurangabad             100
                         9       92976    223  Aurangabad             100
                                 92977    223  Aurangabad             100

                                        SectionNo  votersl houseno  \
PollingBoothNo SectionNo houseno
1              1         04      1003           1     1199      04
                         1       0              1        1       1
                         10      76             1       77      10
                         11      84             1       85      11
                         12      103            1      104      12
...                                           ...      ...     ...
100            3         6       92906          3      114       6
                         7       92930          3      138       7
                         8       92934          3      142       8
                         9       92976          3      184       9
                                 92977          3      185       9

                                             VIDNo            VoterNameEng  \
PollingBoothNo SectionNo houseno
1              1         04      1003   NCY2723419             SAVITA DEVI
                         1       0      NCY2630614            saurav kumar
                         10      76     NCY0417469               Mina Devi
                         11      84     NCY1598366  Nand Keshwar Chaudhari
                         12      103    NCY0685719          Naurangi Singh
...                                            ...                     ...
100            3         6       92906  FPX2422855           Krishna Singh
                         7       92930  NCY2412849                Raja Ram
                         8       92934  FPX5378765       Tejanarayan Singh
                         9       92976  NCY2412757               Mina Devi
                                 92977  NCY2412765               Mira Devi

                                                Votername     Sex  \
PollingBoothNo SectionNo houseno
1              1         04      1003          सविता देवी  Female
                         1       0             सौरव कुमार    Male
                         10      76             मीना देवी  Female
                         11      84     नंद केश्वार चौधरी    Male
                         12      103          नौरंगी सिंह    Male
...                                                   ...     ...
100            3         6       92906         कृष्ण सिंह    Male
                         7       92930           राजा राम    Male
                         8       92934     तेजनारायण सिंह    Male
                         9       92976          मीना देवी  Female
                                 92977          मीरा देवी  Female

                                          relationNameEng   relationname  \
PollingBoothNo SectionNo houseno
1              1         04      1003       SHRAVAN KUMAR    श्रवण कुमार
                         1       0           ashok prasad    अशोक प्रसाद
                         10      76      Sundar Chaudhari    सुंदर चौधरी
                         11      84     Saharaj Chaudhari    सहराज चौधरी
                         12      103         Dashai Singh       दशई सिंह
...                                                   ...            ...
100            3         6       92906    Jagadayal Singh    जगदयाल सिंह
                         7       92930       Bijali Mochi     बिजली मोची
                         8       92934  Shiv Nandan Singh  शिव नंदन सिंह
                         9       92976    Niranjan Prasad  निरंजन प्रसाद
                                 92977          Binod lal      विनोद लाल

                                       relation  Age SectionName  \
PollingBoothNo SectionNo houseno
1              1         04      1003   Husband   28      जम्होर
                         1       0       Father   22      जम्होर
                         10      76     Husband   69      जम्होर
                         11      84      Father   74      जम्होर
                         12      103     Father   84      जम्होर
...                                         ...  ...         ...
100            3         6       92906   Father   68  ढोढ़ीबिगहा
                         7       92930   Father   77  ढोढ़ीबिगहा
                         8       92934   Father   73  ढोढ़ीबिगहा
                         9       92976  Husband   64  ढोढ़ीबिगहा
                                 92977  Husband   64  ढोढ़ीबिगहा

                                       SectionNameEng  \
PollingBoothNo SectionNo houseno
1              1         04      1003          Jamhor
                         1       0             Jamhor
                         10      76            Jamhor
                         11      84            Jamhor
                         12      103           Jamhor
...                                               ...
100            3         6       92906   DhodhiBigaha
                         7       92930   DhodhiBigaha
                         8       92934   DhodhiBigaha
                         9       92976   DhodhiBigaha
                                 92977   DhodhiBigaha

                                                   PollingStationAddressEn  \
PollingBoothNo SectionNo houseno
1              1         04      1003               Uchcha Vighalay Jamhor
                         1       0                  Uchcha Vighalay Jamhor
                         10      76                 Uchcha Vighalay Jamhor
                         11      84                 Uchcha Vighalay Jamhor
                         12      103                Uchcha Vighalay Jamhor
...                                                                    ...
100            3         6       92906  Utkramit Madhya Vidyalay Bajitapur
                         7       92930  Utkramit Madhya Vidyalay Bajitapur
                         8       92934  Utkramit Madhya Vidyalay Bajitapur
                         9       92976  Utkramit Madhya Vidyalay Bajitapur
                                 92977  Utkramit Madhya Vidyalay Bajitapur

                                                  PollingStationAddress
PollingBoothNo SectionNo houseno
1              1         04      1003               उच्च विघालय  जम्होर
                         1       0                  उच्च विघालय  जम्होर
                         10      76                 उच्च विघालय  जम्होर
                         11      84                 उच्च विघालय  जम्होर
                         12      103                उच्च विघालय  जम्होर
...                                                                 ...
100            3         6       92906  उत्क्रमित मध्य विद्यालय बजितपुर
                         7       92930  उत्क्रमित मध्य विद्यालय बजितपुर
                         8       92934  उत्क्रमित मध्य विद्यालय बजितपुर
                         9       92976  उत्क्रमित मध्य विद्यालय बजितपुर
                                 92977  उत्क्रमित मध्य विद्यालय बजितपुर

[13714 rows x 18 columns]

In [19]:
df[df.MidNameEng=='Sarma']

,AC_No,ACNameEn,PollingBoothNo,SectionNo,votersl,houseno,VIDNo,VoterNameEng,Votername,Sex,...,relationname,relation,Age,SectionName,SectionNameEng,PollingStationAddressEn,PollingStationAddress,FirstNameEng,MidNameEng,LastNameEng
50615,223,Aurangabad,54,1,686,107,NCY0544965,Ramachandra Sarma,रामचंद्र शर्मा,Male,...,बाल केश्वर शर्मा,Father,87,फेसर,Fesar,Uchch Madhy Vidyalay Fesar,उच्च मध्य विद्यालय फेसर,Ramachandra,Sarma,None
69036,223,Aurangabad,74,1,260,23,NCY0168070,Vrijamohan Sarma,वृजमोहन शर्मा,Male,...,अलखदेव शर्मा,Father,35,ममका,Mamka,Utkramit Madhya Vidyalay Mamaka,उत्क्रमित मध्य विद्यालय ममका,Vrijamohan,Sarma,None

In [40]:
# Q.7: 'spellchecker' is the required library for spelling check and correction in python.

df.VoterNameEng=df.VoterNameEng.str.strip().str.replace('Sarma','Sharma')
df.VoterNameEng=df.VoterNameEng.str.strip().str.replace('Yadv','Yadav')

In [41]:
df[df.LastNameEng=='Yadav']

,AC_No,ACNameEn,PollingBoothNo,SectionNo,votersl,houseno,VIDNo,VoterNameEng,Votername,Sex,...,relationname,relation,Age,SectionName,SectionNameEng,PollingStationAddressEn,PollingStationAddress,FirstNameEng,MidNameEng,LastNameEng
1000,223,Aurangabad,1,1,1001,65,FPX0489799,Devi Dayal Yadav,देवी दयाल यादव,Male,...,डोमन यादव,Father,68,जम्होर,Jamhor,Uchcha Vighalay Jamhor,उच्च विघालय जम्होर,Devi,Dayal,Yadav
2411,223,Aurangabad,3,1,289,15,FPX2114999,Sukh Dev Yadav,सुख देव यादव,Male,...,धनेश्वार यादव,Father,72,जम्होर,Jamhor,Uchcha Vighalay Jamhor Purwi Madhya Bhag,उच्च विघालय जम्होर पूर्वी मध्य भाग,Sukh,Dev,Yadav
2675,223,Aurangabad,3,1,553,29,NCY0507624,Shiv Narayan Yadav,शिव नारायण यादव,Male,...,इंद्र देव यादव,Father,54,जम्होर,Jamhor,Uchcha Vighalay Jamhor Purwi Madhya Bhag,उच्च विघालय जम्होर पूर्वी मध्य भाग,Shiv,Narayan,Yadav
2677,223,Aurangabad,3,1,555,29,NCY0507475,Dev Narayan Yadav,देव नारायण यादव,Male,...,इंद्र देव यादव,Father,55,जम्होर,Jamhor,Uchcha Vighalay Jamhor Purwi Madhya Bhag,उच्च विघालय जम्होर पूर्वी मध्य भाग,Dev,Narayan,Yadav
2692,223,Aurangabad,3,1,570,29,FPX5585500,Upendra Kumar Yadav,उपेन्द्र कुमार यादव,Male,...,ज्ञानी यादव,Father,41,जम्होर,Jamhor,Uchcha Vighalay Jamhor Purwi Madhya Bhag,उच्च विघालय जम्होर पूर्वी मध्य भाग,Upendra,Kumar,Yadav
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91117,223,Aurangabad,98,3,268,3,NCY0698928,Shiv Charan Yadav,शिव चरण यादव,Male,...,लालजी यादव,Father,63,बाल बिगहा,Bal Bigaha,Prathamik Vidyalay Tendua Dan,प्राथमिक विद्यालय तेन्दुआ दान,Shiv,Charan,Yadav
91497,223,Aurangabad,98,3,648,19,FPX0208066,Ram Sundar Yadav,राम सुंदर यादव,Male,...,चेतन यादव,Father,40,बाल बिगहा,Bal Bigaha,Prathamik Vidyalay Tendua Dan,प्राथमिक विद्यालय तेन्दुआ दान,Ram,Sundar,Yadav
92510,223,Aurangabad,99,2,689,10,NCY2412344,Satyendra Singh Yadav,सत्येन्द्र सिंह यादव,Male,...,देवनारायण यादव,Father,40,पोईवाँ लोहानी,Poivan Lohani,Madhya Vidyalay Poiva,मध्य विद्यालय पोइवां,Satyendra,Singh,Yadav
92653,223,Aurangabad,99,2,832,18,NCY2412658,Vishundev Singh Yadav,विशुनदेव सिंह यादव,Male,...,झूमन सिंह यादव,Father,60,पोईवाँ लोहानी,Poivan Lohani,Madhya Vidyalay Poiva,मध्य विद्यालय पोइवां,Vishundev,Singh,Yadav
92726,223,Aurangabad,99,2,905,28,NCY2412641,Devnarayan Singh Yadav,देवनारायण सिंह यादव,Male,...,बुधराम सिंह,Father,66,पोईवाँ लोहानी,Poivan Lohani,Madhya Vidyalay Poiva,मध्य विद्यालय पोइवां,Devnarayan,Singh,Yadav

In [24]:
df[(df['Age']<30) & (df['Sex']=='Female')].groupby('PollingBoothNo').VIDNo.count()

PollingBoothNo
1      159
2       93
3      111
4       72
5       42
      ...
96     133
97      60
98     169
99     101
100    104
Name: VIDNo, Length: 100, dtype: int64

In [22]:
df.groupby('PollingBoothNo').VIDNo.count()

PollingBoothNo
1      1237
2       886
3      1257
4       999
5       864
       ...
96     1280
97     1040
98      992
99      972
100     615
Name: VIDNo, Length: 100, dtype: int64

In [32]:
df[(df['Age']<30) & (df['Sex']=='Female')].groupby('PollingBoothNo').VIDNo.count().sort_values()

PollingBoothNo
45     29
5      42
71     47
10     50
80     52
     ...
98    169
68    170
54    173
48    188
53    204
Name: VIDNo, Length: 100, dtype: int64